#pragma once

#include "BuildConfiguration.hpp"

#include <filesystem>

namespace Levye {

/**
 * @brief Builds LevyeKit game projects using CMake.
 *
 * BuildCommand configures the project's CMake build directory and invokes the
 * native build system generated by CMake.
 */
class BuildCommand {
public:
  /**
   * @brief Configures and builds a LevyeKit project.
   *
   * @param projectDirectory Root directory of the project.
   * @param configuration Build configuration to compile.
   * @return True when configuration and compilation succeed.
   */
  static bool Execute(const std::filesystem::path &projectDirectory,
                      BuildConfiguration configuration);
};

} // namespace Levye