#pragma once

#include <filesystem>

namespace Levye {

/**
 * @brief Builds LevyeKit game projects using CMake.
 *
 * BuildCommand configures the project's CMake build directory and invokes the
 * native build system generated by CMake.
 */
class BuildCommand {
public:
  /**
   * @brief Configures and builds a LevyeKit project.
   *
   * The project is configured in Debug mode and built inside its Build
   * directory.
   *
   * @param projectDirectory Root directory containing levye.project and the
   *        project's CMakeLists.txt.
   * @return True when both CMake configuration and compilation succeed.
   */
  static bool Execute(const std::filesystem::path &projectDirectory);
};

} // namespace Levye